services:
  postgres:
    image: postgres:16-alpine
    container_name: medcore_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: medcore_hms
    ports:
      - "5432:5432"
    volumes:
      - medcore_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medcore_hms"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: medcore_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - medcore_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  medcore_pgdata:
  medcore_redisdata:
