services:
  postgres:
    image: postgres:16-alpine
    container_name: medcore_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: medcore_hms
    ports:
      - "5432:5432"
    volumes:
      - medcore_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medcore_hms"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: medcore_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - medcore_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: medcore_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgrespassword@postgres:5432/medcore_hms?schema=public
      DIRECT_URL: postgresql://postgres:postgrespassword@postgres:5432/medcore_hms?schema=public
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3001:3001"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: medcore_web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost/api
    depends_on:
      - api
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.25-alpine
    container_name: medcore_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web

volumes:
  medcore_pgdata:
  medcore_redisdata:
